
'use strict';
const YA_BUDGET_DEFAULTS={people:2,rooms:1,rate:4.3,kamataNights:6,atamiNights:3,flight:2200,baggage:350,baggageIncluded:false,kamataHotel:10500,atamiHotel:13000,food:3700,railArrive:300,railTransfer:2300,railReturn:1780,railShimoda:4420,railIto:700,railFuji:1800,railThemeA:750,railThemeC:1400,railKamakura:2200,railYamate:1050,railTogoshi:500,visitTogoshi:false,day8Choice:'atami',day9Choice:'undecided',cityTransit:1000,coastBus:800,otherRmb:500,otherJpy:4000,reserve:10};
function readBudget(){try{const current=JSON.parse(localStorage.getItem('ya-budget-v3'));if(current){if(current.day9Choice==='hakone')current.day9Choice='undecided';delete current.railHakone;return current;}const old=JSON.parse(localStorage.getItem('ya-budget-v2'))||{};const shared=['people','rooms','rate','atamiNights','flight','baggage','baggageIncluded','atamiHotel','food','railReturn','railShimoda','railIto','day8Choice','day9Choice','cityTransit','coastBus','otherRmb','otherJpy','reserve'];const migrated={};for(const key of shared)if(Object.hasOwn(old,key))migrated[key]=old[key];if(old.yokohamaNights!==undefined)migrated.kamataNights=old.yokohamaNights;if(old.yokohamaHotel!==undefined)migrated.kamataHotel=old.yokohamaHotel;if(migrated.day9Choice==='hakone')migrated.day9Choice='undecided';return migrated;}catch{return {};}}
let yaBudget={...YA_BUDGET_DEFAULTS,...readBudget()};
function calculateYABudget(b){
 for(const[key,value]of Object.entries(b)){if(typeof value==='boolean'||key==='day8Choice'||key==='day9Choice')continue;const n=Number(value);if(value===''||!Number.isFinite(n)||n<0)throw new RangeError('预算项 '+key+' 必须是非负有限数字');}
 if(!['atami','ito'].includes(b.day8Choice)||!['undecided','rest','shimoda','fuji'].includes(b.day9Choice))throw new RangeError('D8/D9须选择列出的互斥路线');
 for(const key of ['people','rooms','kamataNights','atamiNights'])if(!Number.isInteger(Number(b[key]))||Number(b[key])<(key==='people'||key==='rooms'?1:0))throw new RangeError(key+' 须为有效整数');
 if(!(Number(b.rate)>0)||Number(b.reserve)>100)throw new RangeError('汇率或预备金超出范围');
 const nights=Number(b.kamataNights)+Number(b.atamiNights),days=nights+1,rate=Number(b.rate)/100,people=Number(b.people),rooms=Number(b.rooms);
 const air=people*(Number(b.flight)+(b.baggageIncluded?0:Number(b.baggage)));
 const lodging=rooms*(Number(b.kamataNights)*Number(b.kamataHotel)+Number(b.atamiNights)*Number(b.atamiHotel))*rate;
 const meals=people*days*Number(b.food)*rate;
 const lineItems=[['D1 羽田→蒲田（铁路占位）',b.railArrive],['主题A 自由之丘→代官山→中目黑',b.railThemeA],['主题B 镰仓（JR＋江之电四段）',b.railKamakura],['主题C 吉祥寺→下北泽',b.railThemeC],['主题D 山手→元町（日归）',b.railYamate],['D7 蒲田→热海（普通线占位）',b.railTransfer],['D10 热海→羽田普通线（占位）',b.railReturn],['其他未列市内交通余量',b.cityTransit],['热海海岸公交余量',b.coastBus]];
 if(b.visitTogoshi)lineItems.push(['机动日 蒲田↔户越银座（占位）',b.railTogoshi]);
 if(b.day8Choice==='ito')lineItems.push(['D8 热海↔伊东普通车',b.railIto]);
 if(b.day9Choice==='shimoda')lineItems.push(['D9 热海↔伊豆急下田普通车',b.railShimoda]);
 if(b.day9Choice==='fuji')lineItems.push(['D9 富士市完整往返（占位）',b.railFuji]);
 const transport=people*lineItems.reduce((s,[,price])=>s+Number(price),0)*rate;
 const other=people*Number(b.otherRmb)+Number(b.otherJpy)*rate,subtotal=air+lodging+meals+transport+other,reserve=subtotal*Number(b.reserve)/100;
 return{days,nights,air,lodging,meals,transport,other,subtotal,reserve,total:subtotal+reserve,lineItems};
}
window.YA_BUDGET={calculate:calculateYABudget,get state(){return{...yaBudget};},get defaults(){return{...YA_BUDGET_DEFAULTS};}};
function inputHTML(key,label,unit,min=0,max=100000,step=1){return `<label>${label}<span class="input-unit"><input data-budget="${key}" type="number" min="${min}" max="${max}" step="${step}" inputmode="decimal"><span>${unit}</span></span></label>`;}
function displayMoney(n){return '人民币 '+Math.round(n).toLocaleString('zh-CN')+' 元';}
function budgetForm(){
 document.getElementById('budget-app').innerHTML=`<div class="budget-grid"><form id="budget-form" novalidate>
 <fieldset><legend>人数、住宿夜数与汇率</legend><div class="budget-fields">${inputHTML('people','同行人数','人',1,8)}${inputHTML('rooms','每晚房间数','间',1,4)}${inputHTML('kamataNights','蒲田住宿','晚',0,20)}${inputHTML('atamiNights','热海住宿','晚',0,20)}${inputHTML('rate','100日元兑换人民币','元',.01,100,.0001)}</div><p class="tip">蒲田6晚＋热海3晚是10天9晚草案。改夜数只重算住宿和餐饮，不自动重排行程与交通。汇率4.3为计算假设。旧版本中自行填写的共同费用与住宿估算会保留，新基地交通使用新占位。</p></fieldset>
 <fieldset><legend>往返航空、双人房与吃饭</legend><div class="budget-fields">${inputHTML('flight','每人往返含税机票','人民币')}${inputHTML('baggage','每人额外行李／选座','人民币')}${inputHTML('kamataHotel','蒲田每房每晚','日元')}${inputHTML('atamiHotel','热海每房每晚','日元')}${inputHTML('food','每天每人餐饮','日元')}</div><label class="budget-option"><input data-budget="baggageIncluded" type="checkbox">机票已含所需行李／选座</label><p class="tip">机票和房价均为可编辑估算，按实际日期、双人入住价、税与取消政策再核；蒲田房价初值不代表酒店报价。</p></fieldset>
 <fieldset><legend>逐项交通 · 每名成人</legend><div class="budget-fields">${inputHTML('railArrive','D1 羽田→蒲田','日元/人')}${inputHTML('railThemeA','主题A 东急三街区','日元/人')}${inputHTML('railKamakura','主题B 镰仓＋江之电四段','日元/人')}${inputHTML('railThemeC','主题C 吉祥寺＋下北泽','日元/人')}${inputHTML('railYamate','主题D 横滨山手往返','日元/人')}${inputHTML('railTransfer','D7 蒲田→热海','日元/人')}${inputHTML('railReturn','D10 热海→羽田','日元/人')}${inputHTML('cityTransit','其他市内交通余量','日元/人')}${inputHTML('coastBus','热海海岸公交余量','日元/人')}</div>
 <p class="tip">蒲田段与转场初值全部是规划占位，不是核实票价。镰仓改为长谷、稻村崎、七里滨，江之电共四段，不能沿用旧三段预算；同一JR全程票不重复加换乘接驳。四主题换日期不增加费用。</p>
 <div class="budget-options"><label class="budget-option"><input data-budget="visitTogoshi" type="checkbox">机动日去户越银座（否则留蒲田休息）</label>${inputHTML('railTogoshi','户越银座往返占位','日元/人')}
 <label class="budget-choice">D8 当天路线<select data-budget="day8Choice"><option value="atami">热海坡地街景／海边（默认）</option><option value="ito">伊东 Orange Beach 半日</option></select></label>${inputHTML('railIto','伊东普通车往返','日元/人')}
 <label class="budget-choice">D9 当天路线<select data-budget="day9Choice"><option value="undecided">暂未决定 · 不计跨城车费</option><option value="rest">留热海休息</option><option value="fuji">富士市（晴天能见度好）</option><option value="shimoda">下田港与佩里路</option></select></label>${inputHTML('railFuji','富士市往返规划占位','日元/人')}${inputHTML('railShimoda','下田普通车往返','日元/人')}</div>
 <p class="tip">热海↔伊东普通车往返700円、下田普通车往返4,420円沿用上一版纸票资料，出发前再核。富士市为可编辑规划占位。D9跨城只计已选的一套；踊り子、新干线、出租车另按实际追加。</p></fieldset>
 <fieldset><legend>其他费用与预备金</legend><div class="budget-fields">${inputHTML('otherRmb','每人签证／保险／上网','人民币')}${inputHTML('otherJpy','全体住宿税／出租车余量','日元')}${inputHTML('reserve','预备金','%',0,100)}</div></fieldset>
 <p id="budget-error" class="budget-error" role="alert" hidden></p><button type="button" class="outline" id="budget-reset">恢复估算初值</button></form>
 <aside class="budget-result" aria-live="polite"><span class="tiny">ESTIMATED TOTAL · CNY</span><p>同行总预算</p><strong id="budget-total">—</strong><p id="budget-per-person"></p><p id="budget-duration"></p><dl id="budget-breakdown"></dl><p class="tip">初值仅供规划，按主题计交通，互斥选项不会叠加。</p></aside></div><details><summary>查看交通预算逐项计费与来源</summary><div id="budget-transport"></div><p class="tip"><a href="https://www.jreast.co.jp/" target="_blank" rel="noopener">JR查询 ↗</a> · <a href="https://www.izukyu.co.jp/fares/" target="_blank" rel="noopener">伊豆急价表 ↗</a></p></details>`;
 document.querySelectorAll('[data-budget]').forEach(el=>{el.type==='checkbox'?el.checked=Boolean(yaBudget[el.dataset.budget]):el.value=yaBudget[el.dataset.budget];el.addEventListener('change',budgetChange);});
 document.getElementById('budget-reset').addEventListener('click',()=>{yaBudget={...YA_BUDGET_DEFAULTS};budgetForm();});renderBudget();
}
function budgetChange(){let errors=[];for(const el of document.querySelectorAll('[data-budget][type=number]')){const n=Number(el.value),bad=el.value.trim()===''||!Number.isFinite(n)||n<Number(el.min)||n>Number(el.max)||(Number(el.step)===1&&!Number.isInteger(n));el.setAttribute('aria-invalid',String(bad));if(bad)errors.push(el.closest('label').firstChild.textContent.trim());}const warning=document.getElementById('budget-error');warning.hidden=!errors.length;warning.textContent=errors.length?'请修正 '+errors.join('、')+'：当前合计保留上一次有效输入。':'';if(errors.length)return;document.querySelectorAll('[data-budget]').forEach(el=>{yaBudget[el.dataset.budget]=el.type==='checkbox'?el.checked:el.tagName==='SELECT'?el.value:Number(el.value);});renderBudget();}
function renderBudget(){const b=yaBudget,r=calculateYABudget(b);document.getElementById('budget-total').textContent=displayMoney(r.total);document.getElementById('budget-per-person').textContent='平均每人 '+displayMoney(r.total/b.people)+' · 含 '+b.reserve+'% 预备金';document.getElementById('budget-duration').textContent=r.days+' 天 / '+r.nights+' 晚 · '+b.rooms+' 间房';document.getElementById('budget-breakdown').innerHTML=[['往返航空',r.air],['住宿（每房每晚）',r.lodging],['餐饮（每天每人）',r.meals],['已选交通',r.transport],['其他费用',r.other],['预备金',r.reserve]].map(([name,n])=>`<div><dt>${name}</dt><dd>${displayMoney(n)}</dd></div>`).join('');document.getElementById('budget-transport').innerHTML=r.lineItems.map(([name,n])=>`<p>${name}：${Number(n).toLocaleString('zh-CN')} 円/人 · 同行 ${b.people} 人 ${Number(n*b.people).toLocaleString('zh-CN')} 円</p>`).join('');try{localStorage.setItem('ya-budget-v3',JSON.stringify(b));}catch{}window.dispatchEvent(new Event('ya:budget-change'));}
budgetForm();
