'use strict';
// Prices except the explicitly marked Shimoda/Ito ordinary rail fares are editable planning estimates, not quotes.
const YA_BUDGET_DEFAULTS={people:2,rooms:1,rate:4.3,yokohamaNights:6,atamiNights:3,flight:2200,baggage:350,baggageIncluded:false,yokohamaHotel:10500,atamiHotel:13000,food:3700,railArrive:530,railTransfer:2100,railReturn:1780,railShimoda:4420,railIto:700,railHakone:2300,railTokyoA:1150,railTokyoB:1100,railKamakura:1560,railYokohamaD6:400,railZushi:1100,visitZushi:false,day8Choice:'atami',day9Choice:'undecided',cityTransit:1000,coastBus:800,otherRmb:500,otherJpy:4000,reserve:10};
let yaBudget={...YA_BUDGET_DEFAULTS,...readBudget()};
function readBudget(){try{return JSON.parse(localStorage.getItem('ya-budget-v2'))||{};}catch{return {};}}
function calculateYABudget(b){for(const [key,value] of Object.entries(b)){if(typeof value==='boolean'||key==='day8Choice'||key==='day9Choice')continue;const number=Number(value);if(value===''||!Number.isFinite(number)||number<0)throw new RangeError('预算项 '+key+' 必须是非负有限数字');}if(!['atami','ito'].includes(b.day8Choice)||!['undecided','rest','shimoda','hakone'].includes(b.day9Choice))throw new RangeError('D8或D9须从列出的互斥路线中选择');for(const key of ['people','rooms','yokohamaNights','atamiNights']){if(!Number.isInteger(Number(b[key]))||Number(b[key])<(key==='people'||key==='rooms'?1:0))throw new RangeError(key+' 须为有效整数');}if(!(Number(b.rate)>0)||Number(b.reserve)>100)throw new RangeError('汇率或预备金超出范围');const nights=Number(b.yokohamaNights)+Number(b.atamiNights),days=nights+1,rate=Number(b.rate)/100,people=Number(b.people),rooms=Number(b.rooms);
 const air=people*(Number(b.flight)+(b.baggageIncluded?0:Number(b.baggage)));
 const lodging=rooms*(Number(b.yokohamaNights)*Number(b.yokohamaHotel)+Number(b.atamiNights)*Number(b.atamiHotel))*rate;
 const meals=people*days*Number(b.food)*rate;
 const lineItems=[['D1 羽田→横滨（京急＋JR）',b.railArrive],['D3 镰仓海岸（JR＋江之电三段）',b.railKamakura],['D4 东京银座日归（整段占位）',b.railTokyoA],['D5 东京东横线日归（券＋JR接驳）',b.railTokyoB],[b.visitZushi?'D6 逗子海岸半日替换':'D6 美国山＋港见丘半日',b.visitZushi?b.railZushi:b.railYokohamaD6],['D7 横滨→热海（规划占位）',b.railTransfer],['D10 热海→羽田普通线（规划占位）',b.railReturn],['其他未列市内交通余量',b.cityTransit],['热海海岸公交余量',b.coastBus]];
 if(b.day8Choice==='ito')lineItems.push(['D8 热海↔伊东普通车',b.railIto]);if(b.day9Choice==='shimoda')lineItems.push(['D9 热海↔伊豆急下田普通车',b.railShimoda]);if(b.day9Choice==='hakone')lineItems.push(['D9 箱根汤本短段完整往返规划占位',b.railHakone]);
 const transport=people*lineItems.reduce((s,[,price])=>s+Number(price),0)*rate;
 const other=people*Number(b.otherRmb)+Number(b.otherJpy)*rate;
 const subtotal=air+lodging+meals+transport+other,reserve=subtotal*Number(b.reserve)/100,total=subtotal+reserve;
 return {days,nights,air,lodging,meals,transport,other,subtotal,reserve,total,lineItems};}
window.YA_BUDGET={calculate:calculateYABudget,get state(){return {...yaBudget};},get defaults(){return {...YA_BUDGET_DEFAULTS};}};
function inputHTML(key,label,unit,min=0,max=100000,step=1){return `<label>${label}<span class="input-unit"><input data-budget="${key}" type="number" min="${min}" max="${max}" step="${step}" inputmode="decimal"><span>${unit}</span></span></label>`;}
function displayMoney(n){return '人民币 '+Math.round(n).toLocaleString('zh-CN')+' 元';}
function budgetForm(){document.getElementById('budget-app').innerHTML=`<div class="budget-grid"><form id="budget-form" novalidate><fieldset><legend>人数、住宿夜数与汇率</legend><div class="budget-fields">${inputHTML('people','同行人数','人',1,8,1)}${inputHTML('rooms','每晚房间数','间',1,4,1)}${inputHTML('yokohamaNights','横滨住宿','晚',0,20,1)}${inputHTML('atamiNights','热海住宿','晚',0,20,1)}${inputHTML('rate','100 日元兑换人民币','元',.01,100,.0001)}</div><p class="tip">当前6＋3晚只是草案。改住宿夜数只重算住宿和餐饮，D1–D10交通仍按10天示例，需要重新排路后再购票。汇率4.3是可改的计算假设，不是实时银行报价。</p></fieldset><fieldset><legend>往返航空、双人房与吃饭</legend><div class="budget-fields">${inputHTML('flight','每人往返含税机票','人民币')} ${inputHTML('baggage','每人往返额外行李／选座','人民币')} ${inputHTML('yokohamaHotel','横滨每房每晚','日元')} ${inputHTML('atamiHotel','热海每房每晚','日元')} ${inputHTML('food','每天每人餐饮','日元')}</div><label class="budget-option"><input data-budget="baggageIncluded" type="checkbox">机票报价已含所需行李和选座，不重复加额外项</label><p class="tip">机票和酒店初值均为规划估算。上海直飞羽田的实际航班、行李、双人入住价、早餐、税和取消政策需按选定日期核验。</p></fieldset><fieldset><legend>逐项交通 · 每名成人</legend><div class="budget-fields">${inputHTML('railArrive','D1 羽田→横滨','日元/人')} ${inputHTML('railTransfer','D7 横滨→热海','日元/人')} ${inputHTML('railReturn','D10 热海→羽田','日元/人')} ${inputHTML('railShimoda','D9 下田普通车往返','日元/人')} ${inputHTML('cityTransit','全程其他市内交通','日元/人')} ${inputHTML('coastBus','热海海岸公交余量','日元/人')}</div><p class="tip">只有热海↔伊豆急下田普通车往返初值 4,420 円来自2026-03-14伊豆急价表（单程纸票2,210）。羽田、横滨跨城与市内交通初值均只是待按实际线路替换的规划占位；本表不把“踊り子”特急费混入普通车票。</p><div class="budget-options"><label class="budget-option"><input data-budget="visitIto" type="checkbox">可选 D8 伊东半日：热海↔伊东普通车</label>${inputHTML('railIto','伊东普通车往返','日元/人')}<label class="budget-option"><input data-budget="visitHakone" type="checkbox">可选 D9 仅箱根汤本站附近</label>${inputHTML('railHakone','箱根汤本整段往返','日元/人')}</div><p class="tip">伊东普通车热海↔伊东单程纸票350円、往返700円。箱根初值含未核实的热海—小田原往返估算，出发前须用官方票价替换；默认不计入。</p></fieldset><fieldset><legend>全程其他费用与预备金</legend><div class="budget-fields">${inputHTML('otherRmb','每人全程签证／保险／上网','人民币')} ${inputHTML('otherJpy','全体合计住宿税／出租余量等','日元')} ${inputHTML('reserve','预备金','%',0,100,1)}</div></fieldset><p id="budget-error" class="budget-error" role="alert" hidden></p><button type="button" class="outline" id="budget-reset">恢复估算初值</button></form><aside class="budget-result" aria-live="polite"><span class="tiny">ESTIMATED TOTAL · CNY</span><p>同行总预算</p><strong id="budget-total">—</strong><p id="budget-per-person"></p><p id="budget-duration"></p><dl id="budget-breakdown"></dl><p class="tip">当前数值是规划模拟，不代表票价或酒店预订报价；已选交通列表与假设在下方逐项显示。</p></aside></div><details><summary>查看交通预算逐项计费与官方来源</summary><div id="budget-transport"></div><p class="tip"><a href="https://www.izukyu.co.jp/fares/" target="_blank" rel="noopener">伊豆急价表 ↗</a> · <a href="https://www.izukyu.co.jp/fares/express.php" target="_blank" rel="noopener">踊り子特急费另付 ↗</a></p></details>`;
 document.querySelectorAll('[data-budget]').forEach(el=>{el.type==='checkbox'?el.checked=Boolean(yaBudget[el.dataset.budget]):el.value=yaBudget[el.dataset.budget];el.addEventListener('change',budgetChange);});document.getElementById('budget-reset').addEventListener('click',()=>{yaBudget={...YA_BUDGET_DEFAULTS};document.querySelectorAll('[data-budget]').forEach(el=>{el.type==='checkbox'?el.checked=Boolean(yaBudget[el.dataset.budget]):el.value=yaBudget[el.dataset.budget];el.removeAttribute('aria-invalid');});document.getElementById('budget-error').hidden=true;renderBudget();});renderBudget();}
function budgetChange(){let errors=[];for(const el of document.querySelectorAll('[data-budget][type=number]')){const n=Number(el.value),bad=el.value.trim()===''||!Number.isFinite(n)||n<Number(el.min)||n>Number(el.max)||(Number(el.step)===1&&!Number.isInteger(n));el.setAttribute('aria-invalid',String(bad));if(bad)errors.push(el.closest('label').childNodes[0].textContent.trim());}const warning=document.getElementById('budget-error');warning.hidden=!errors.length;warning.textContent=errors.length?'请修正 '+errors.join('、')+'：不能为空、为负数或超出范围。当前合计维持上一次有效输入。':'';if(errors.length)return;document.querySelectorAll('[data-budget]').forEach(el=>{yaBudget[el.dataset.budget]=el.type==='checkbox'?el.checked:el.tagName==='SELECT'?el.value:Number(el.value);});renderBudget();}
function renderBudget(){const b=yaBudget,result=calculateYABudget(b);document.getElementById('budget-total').textContent=displayMoney(result.total);document.getElementById('budget-per-person').textContent='平均每人 '+displayMoney(result.total/b.people)+' · 含 '+b.reserve+'% 预备金';document.getElementById('budget-duration').textContent=result.days+' 天 / '+result.nights+' 晚 · '+b.rooms+' 间房';document.getElementById('budget-breakdown').innerHTML=[['往返航空',result.air],['住宿（每房每晚）',result.lodging],['餐饮（每天每人）',result.meals],['已选交通',result.transport],['其他费用',result.other],['预备金',result.reserve]].map(([name,n])=>`<div><dt>${name}</dt><dd>${displayMoney(n)}</dd></div>`).join('');document.getElementById('budget-transport').innerHTML=result.lineItems.map(([name,n])=>`<p>${name}：${Number(n).toLocaleString('zh-CN')} 円/人 · 同行 ${b.people} 人 ${Number(n*b.people).toLocaleString('zh-CN')} 円</p>`).join('');try{localStorage.setItem('ya-budget-v2',JSON.stringify(b));}catch{}window.dispatchEvent(new Event('ya:budget-change'));}
budgetForm();
// 明细与互斥选择：D8 和 D9 的路线、照片与预算由同一状态驱动。
const tokyoFields=document.querySelectorAll('#budget-form fieldset')[2].querySelector('.budget-fields');
tokyoFields.insertAdjacentHTML('beforeend',inputHTML('railKamakura','D3 镰仓JR＋江之电','日元/人')+inputHTML('railTokyoA','D4 银座日归整段','日元/人')+inputHTML('railTokyoB','D5 东横线日归整段','日元/人')+inputHTML('railYokohamaD6','D6 美国山＋港见丘半日','日元/人')+inputHTML('railZushi','D6 逗子替换半日','日元/人'));
const options=document.querySelector('#budget-form .budget-options');
options.innerHTML=`<label class="budget-choice">D8 当天路线<select data-budget="day8Choice"><option value="atami">热海坡地街景／海边（默认）</option><option value="ito">伊东 Orange Beach 半日</option></select></label>${inputHTML('railIto','D8 伊东普通车往返','日元/人')}<label class="budget-choice">D9 当天路线<select data-budget="day9Choice"><option value="undecided">暂未决定 · 先不计跨城车费</option><option value="rest">确定留在热海休息</option><option value="shimoda">下田港与佩里路</option><option value="hakone">仅箱根汤本站附近</option></select></label>${inputHTML('railHakone','D9 箱根完整往返估算','日元/人')}<label class="budget-option"><input data-budget="visitZushi" type="checkbox">D6 逗子海岸替换美国山＋港见丘</label>`;
document.querySelectorAll('[data-budget="railKamakura"],[data-budget="railTokyoA"],[data-budget="railTokyoB"],[data-budget="railYokohamaD6"],[data-budget="railZushi"],[data-budget="railIto"],[data-budget="railHakone"],[data-budget="day8Choice"],[data-budget="day9Choice"],[data-budget="visitZushi"]').forEach(el=>{el.type==='checkbox'?el.checked=Boolean(yaBudget[el.dataset.budget]):el.value=yaBudget[el.dataset.budget];el.addEventListener('change',budgetChange);});
const budgetTips=document.querySelectorAll('#budget-form .tip');
budgetTips[0].textContent='当前横滨6晚＋热海3晚只是草案。改住宿夜数只重算住宿和餐饮，D1–D10交通仍按10天示例，需要重新排路后再购票。汇率4.3是可改的计算假设，不是实时银行报价。';
for(const [key,label] of Object.entries({railTransfer:'D7 横滨→热海',railReturn:'D10 热海→羽田',railShimoda:'D9 下田普通车往返'})){document.querySelector(`input[data-budget="${key}"]`).closest('label').firstChild.textContent=label;}
budgetTips[2].textContent='D3镰仓：JR樱木町↔镰仓440×2＋江之电三段200＋220＋260＝1,560円/人。D8伊东成人普通往返700円，只在选伊东时计入。D9下田普通往返4,420円、箱根全段为可编辑估算，仅选其一时计入；默认未决定，暂不计跨城车费。银座日默认两张JR票约1,150円；临时坐Metro或有乐町一站JR请补其他市内交通。东横线日默认东急一日券780＋樱木町JR接驳纸票160×2＝1,100円/人。';
budgetTips[3].textContent='箱根估算包含热海—小田原待核普通车往返，以及小田原—箱根汤本站普通车360×2；仅去汤本站附近不推荐1,580円全线日券。D9改下田时不能再计箱根票；踊り子特急若选择需另加每名成人每方向事前特急券1,560円，不含在普通票中。';
renderBudget();
